import type { OrugaConfig } from "@oruga-ui/oruga-next";
import { isTrueish } from "@oruga-ui/oruga-next";

const bulmaConfig: OrugaConfig = {
    override: true,
    button: {
        rootClass: "button",
        sizeClass: "is-",
        variantClass: "is-",
        roundedClass: "is-rounded",
        expandedClass: "is-fullwidth",
        loadingClass: "is-loading",
        outlinedClass: (variant) => {
            if (!variant) return "is-outlined";
            return `is-${variant} is-outlined`;
        },
        invertedClass: (variant) => {
            if (!variant) return "is-inverted";
            return `is-${variant} is-inverted`;
        },
    },
    breadcrumb: {
        rootClass: "breadcrumb",
        variantClass: "is-",
        sizeClass: "is-",
        positionClass: "is-",
        itemClass: "",
        activeClass: "is-active",
        disabledClass: "is-disabled",
    },
    collapse: {
        rootClass: "collapse",
        positionClass: "is-",
        triggerClass: "collapse-trigger",
        expandedClass: "is-expanded",
        contentClass: "collapse-content",
    },
    carousel: {
        rootClass: "carousel",
        overlayClass: "is-overlay",
        wrapperClass: "carousel-scene",
        itemsClass: "carousel-items",
        itemsDraggingClass: "is-dragging",
        iconClass: "carousel-arrow",
        iconPrevClass: "has-icons-left icon-prev",
        iconNextClass: "has-icons-right icon-next",
        iconAutoplayClass: "icon-autoplay",
        indicatorsClass: "carousel-indicator",
        indicatorClass: "indicator-item",
        indicatorsInsideClass: "is-inside",
        indicatorsPositionClass: "is-",
        indicatorItemClass: "indicator-style",
        indicatorItemActiveClass: "is-active",
        indicatorItemStyleClass: "is-",
        itemClass: "carousel-item",
        itemActiveClass: "is-active",
    },
    field: {
        rootClass: "field",
        labelClass: "label",
        labelSizeClass: "is-",
        messageClass: "help",
        messageVariantClass: "is-",
        bodyClass: "field-body",
        addonsClass: "has-addons",
        groupedClass: (_, props) => {
            const classes = ["is-grouped"];
            if (!props.block) classes.push("is-grouped-multiline");
            return classes;
        },
        blockClass: "is-block",
        horizontalClass: "is-horizontal",
        horizontalLabelClass: "field-label",
        horizontalBodyClass: "field-body",
    },
    input: {
        rootClass: (_: string, props: Record<string, any>) => {
            const classes = ["control"];
            if (isTrueish(props.icon)) classes.push("has-icons-left");
            return classes.join(" ");
        },
        inputClass: (_: string, props: Record<string, any>) => {
            const classes = ["input"];
            if (isTrueish(props.type == "textarea")) classes.push("textarea");
            return classes.join(" ");
        },
        textareaClass: "is-textarea",
        roundedClass: "is-rounded",
        variantClass: "is-",
        sizeClass: "is-",
        expandedClass: "is-expanded",
        iconLeftClass: "is-left",
        iconRightClass: "is-right",
        counterClass: "help counter",
        hasIconRightClass: "has-icons-right",
    },
    select: {
        rootClass: (_: string, props: Record<string, any>) => {
            const classes = ["select", "control"];
            if (isTrueish(props.size)) classes.push(`is-${props.size}`);
            if (isTrueish(props.rounded)) classes.push("is-rounded");
            if (isTrueish(props.multiple)) classes.push("is-multiple");
            if (isTrueish(props.disabled)) classes.push("is-disabled");
            if (isTrueish(props.icon)) classes.push("has-icons-left");
            if (isTrueish(props.iconRight)) classes.push("has-icons-right");
            return classes.join(" ");
        },
        variantClass: "is-",
        expandedClass: "is-expanded is-fullwidth",
        iconLeftClass: "is-left",
        iconRightClass: "is-right",
        placeholderClass: "is-empty",
        iconRightSpaceClass: "has-icon-right",
        iconLeftSpaceClass: "has-icon-left",
        arrowedClass: "has-arrow",
    },
    icon: {
        rootClass: "icon",
        variantClass: "has-text-",
        sizeClass: "is-",
        clickableClass: "is-clickable",
        spinClass: "is-spin",
    },
    checkbox: {
        rootClass: "checkbox control",
        disabledClass: "is-disabled",
        inputClass: "check",
        labelClass: "control-label",
        variantClass: "is-",
        sizeClass: "is-",
    },
    radio: {
        rootClass: "radio control",
        disabledClass: "is-disabled",
        inputClass: "check",
        labelClass: "control-label",
        variantClass: "is-",
        sizeClass: "is-",
    },
    switch: {
        rootClass: "switch control",
        inputClass: "check",
        positionClass: (value) => `has-${value}-label`,
        roundedClass: "is-rounded",
        labelClass: "control-label",
        sizeClass: "is-",
        variantClass: "is-",
        passiveVariantClass: "is-",
        disabledClass: "is-disabled",
    },
    dropdown: {
        rootClass: "dropdown",
        hoverableClass: "is-hoverable",
        disabledClass: "is-disabled",
        expandedClass: "is-expanded",
        triggerClass: "dropdown-trigger",
        menuClass: "dropdown-menu",
        contentClass: "dropdown-content",
        contentModalClass: "is-modal",
        contentBackdropClass: "has-backdrop",
        itemClass: "dropdown-item",
        itemSelectedClass: "is-active",
        itemFocusedClass: "is-focused",
        itemDisabledClass: "is-disabled",
    },
    autocomplete: {
        rootClass: "autocomplete control",
        itemEmptyClass: "is-disabled",
        itemGroupClass: "has-text-weight-bold",
    },
    tag: {
        rootClass: "tag",
        variantClass: "is-",
        sizeClass: "is-",
        roundedClass: "is-rounded",
        badgeClass: "badge",
        closeClass: "delete is-small",
    },
    taginput: {
        rootClass: "taginput control",
        containerClass: "taginput-container",
        itemClass: "tag",
        sizeClass: "is-",
        variantClass: "is-",
        expandedClass: "is-expanded",
    },
    datepicker: {
        rootClass: "datepicker",
        triggerClass: "datepicker-trigger",
        contentClass: "datepicker-overlay",
        contentBackdropClass: "has-backdrop",
        headerClass: "datepicker-header",
        footerClass: "datepicker-footer",
        tableClass: "datepicker-table",
        tableHeadClass: "datepicker-header",
        tableHeadCellClass: "datepicker-cell",
        prevButtonClass: "button-prev",
        nextButtonClass: "button-next",
        listsClass: "select-list",
        tableBodyClass: (_: string, props: Record<string, any>) => {
            const classes = ["datepicker-body"];
            if (props.events) classes.push(`has-events`);
            return classes.join(" ");
        },
        tableRowClass: "datepicker-row",
        tableCellClass: "datepicker-cell",
        tableCellSelectableClass: "is-selectable",
        tableCellUnselectableClass: "is-unselectable",
        tableCellTodayClass: "is-today",
        tableCellSelectedClass: "is-selected",
        tableCellWithinHoveredClass: "is-within-hovered",
        tableCellFirstHoveredClass: "is-first-hovered",
        tableCellLastHoveredClass: "is-last-hovered",
        tableCellFirstSelectedClass: "is-first-selected",
        tableCellLastSelectedClass: "is-last-selected",
        tableCellWithinSelectedClass: "is-within-selected",
        tableCellInvisibleClass: "",
        tableCellNearbyClass: "is-nearby",
        tableCellEventsClass: "has-event",
        tableEventsClass: "events",
        tableEventClass: "event",
        tableEventVariantClass: "is-",
        tableEventIndicatorClass: "is-",
        monthCellClass: "datepicker-cell",
        monthCellFirstHoveredClass: "is-first-hovered",
        monthCellFirstSelectedClass: "is-first-selected",
        monthCellLastHoveredClass: "is-last-hovered",
        monthCellLastSelectedClass: "is-last-selected",
        monthCellSelectableClass: "is-selectable",
        monthCellSelectedClass: "is-selected",
        monthCellTodayClass: "is-today",
        monthCellUnselectableClass: "is-unselectable",
        monthCellWithinHoveredClass: "is-within-hovered",
        monthCellWithinSelectedClass: "is-within-selected",
        monthClass: "datepicker-table",
        monthTableClass: "datepicker-months",
        monthEventsClass: "events",
        monthEventClass: "event",
        monthEventIndicatorClass: "is-",
        monthEventVariantClass: "is-",
    },
    timepicker: {
        rootClass: "timepicker",
        contentClass: "timepicker-overlay",
        contentBackdropClass: "has-backdrop",
        separatorClass: "timepicker-colon",
        footerClass: "timepicker-footer",
        sizeClass: "is-",
        selectAttrs: {
            rootClass: "select control",
        },
    },
    datetimepicker: {
        datepickerWrapperClass: "datepicker-wrapper",
        timepickerWrapperClass: "timepicker-wrapper",
    },
    slider: {
        rootClass: "slider",
        disabledClass: "is-disabled",
        trackClass: "slider-track",
        fillClass: "slider-fill",
        thumbWrapperClass: "slider-thumb-wrapper",
        thumbWrapperDraggingClass: "is-dragging",
        thumbRoundedClass: "is-rounded",
        variantClass: "is-",
        sizeClass: "is-",
        thumbClass: "slider-thumb",
        tickLabelClass: "slider-tick-label",
        tickHiddenClass: "is-tick-hidden",
        tickClass: "slider-tick",
    },
    table: {
        rootClass: "table-wrapper",
        wrapperClass: "table-inner",
        tableClass: "table",
        borderedClass: "is-bordered",
        stripedClass: "is-striped",
        narrowedClass: "is-narrow",
        hoverableClass: "is-hoverable",
        emptyClass: "is-empty",
        footerClass: "table-footer",
        paginationWrapperClass: "level",
        scrollableClass: "table-container",
        stickyHeaderClass: "has-sticky-header",
        trSelectedClass: "is-selected",
        trDetailedClass: "is-detailed",
        thSortableClass: "is-sortable",
        thSortedClass: "is-current-sort",
        thSortIconClass: "sort-icon",
        thStickyClass: "is-sticky",
        tdStickyClass: "is-sticky",
        thCheckboxClass: "th-checkbox",
        thDetailedClass: "th-chevron-cell",
        tdDetailClass: "chevron-cell",
        thPositionClass: "is-",
        tdPositionClass: "has-text-",
        mobileClass: "is-mobile",
        mobileSortClass: "table-mobile-sort",
    },
    pagination: {
        rootClass: (_: string, props: Record<string, any>) => {
            const classes = ["pagination"];
            if (props.rounded) classes.push("is-rounded");
            return classes.join(" ");
        },
        sizeClass: "is-",
        simpleClass: "is-simple",
        positionClass: "is-",
        roundedClass: "is-rounded",
        listClass: "pagination-list",
        buttonClass: "pagination-link",
        buttonCurrentClass: "is-current",
        buttonDisabledClass: "is-disabled",
        buttonNextClass: "pagination-next",
        buttonPrevClass: "pagination-previous",
        infoClass: "info",
    },
    tooltip: {
        rootClass: "tooltip",
        triggerClass: "tooltip-trigger",
        contentClass: "tooltip-content",
        alwaysClass: "is-always",
        multilineClass: "is-multiline",
        variantClass: "is-",
        positionClass: "is-",
        teleportClass: "is-teleported",
    },
    popover: {
        rootClass: "popover",
        triggerClass: "popover-trigger",
        contentClass: "popover-content",
        contentBackdropClass: "has-backdrop",
        headerClass: "popover-header",
        bodyClass: "popover-body",
        closeClass: "popover-close",
        scrollClipClass: "is-clipped",
    },
    tabs: {
        rootClass: "tabs-wrapper",
        contentClass: "tabs-content",
        multilineClass: "is-multiline",
        expandedClass: "is-fullwidth",
        verticalClass: "is-vertical",
        positionClass: "is-",
        sizeClass: "is-",
        typeClass: "is-",
        listClass: "tabs",
        tabClass: "tab",
        tabIconClass: "tab-icon",
        tabLabelClass: "tab-title",
        tabActiveClass: "is-active",
        tabDisabledClass: "is-disabled",
        tabNextClass: "is-next",
        tabPreviousClass: "is-previous",
        tabPanelClass: "tab-item",
        transitioningClass: "is-transitioning",
    },
    steps: {
        rootClass: "steps-wrapper",
        listClass: "steps",
        verticalClass: "is-vertical",
        animatedClass: "is-animated",
        positionClass: "is-",
        sizeClass: "is-",
        stepClass: "step",
        stepVariantClass: "is-",
        stepActiveClass: "is-active",
        stepPreviousClass: "is-previous",
        stepNextClass: "is-next",
        stepLabelClass: "step-title",
        stepPositionClass: "label-",
        stepClickableClass: "is-clickable",
        markerClass: "step-marker",
        markerRoundedClass: "is-rounded",
        contentClass: "step-content",
        transitioningClass: "is-transitioning",
        stepPanelClass: "step-item",
        navigationClass: "step-navigation",
    },
    menu: {
        rootClass: "menu",
        listClass: "menu-list",
        labelClass: "menu-label",
        itemButtonClass: "menu-item",
        itemButtonActiveClass: "is-active",
        itemButtonDisabledClass: "is-disabled",
        itemSubmenuClass: "submenu",
    },
    skeleton: {
        rootClass: "skeleton",
        animatedClass: "is-animated",
        positionClass: "is-",
        sizeClass: "is-",
        roundedClass: "is-rounded",
        itemClass: "skeleton-block",
    },
    notification: {
        rootClass: "notification",
        wrapperClass: "media",
        contentClass: "media-content",
        iconClass: "media-left",
        closeClass: "delete",
        positionClass: "is-",
        noticeClass: "notices",
        noticePositionClass: "is-",
        variantClass: "is-",
    },
    modal: {
        rootClass: "modal",
        activeClass: "is-active",
        overlayClass: "modal-background",
        contentClass: "modal-content",
        closeClass: "modal-close is-large",
        fullScreenClass: "is-full-screen",
        scrollClipClass: "is-clipped",
    },
    dialog: {
        rootClass: "dialog modal",
        activeClass: "is-active",
        mobileClass: undefined,
        teleportClass: "is-teleported",
        fullscreenClass: "is-fullscreen",
        backdropClass: undefined,
        wrapperClass: "modal-content modal-card",
        textPositionClass: (position: string) => {
            if (position === "left") return "has-text-left";
            else if (position === "center") return "has-text-centered";
            else if (position === "right") return "hast-text-right";
        },
        headerClass: "modal-card-head",
        titleClass: "modal-card-title",
        closeClass: "modal-close is-large",
        closeIconSize: "medium",
        subtitleClass: "modal-card-subtitle",
        bodyClass: "modal-card-body",
        contentClass: undefined,
        figureClass: "image",
        footerClass: "modal-card-foot",
        footerPositionClass: (position: string) => {
            if (position === "left") return "is-justify-content-flex-start";
            if (position === "center") return "is-justify-content-center";
            if (position === "right") return "is-justify-content-flex-end";
        },
        scrollClipClass: "is-clipped",
    },
    sidebar: {
        rootClass: "sidebar",
        overlayClass: "sidebar-background",
        contentClass: "sidebar-content",
        contentMobileClass: "is-",
        activeClass: "is-active",
        positionClass: "is-",
        fullheightClass: "is-fullheight",
        fullwidthClass: "is-fullwidth",
        inlineClass: "is-inline",
        mobileClass: "is-",
        scrollClipClass: "is-clipped",
    },
    listbox: {
        rootClass: "listbox panel",
        selectableClass: "selectable",
        multipleClass: "multiple",
        disabledClass: "is-disabled",
        listClass: "panel-list",
        itemClass: "list-item panel-block",
        itemDisabledClass: "is-disabled",
        itemFocusedClass: "is-focused",
        itemSelectedClass: "is-active",
        filterClass: "list-item panel-block",
        emptyClass: "list-item panel-block is-disabled",
        headerClass: "list-item panel-block",
        footerClass: "list-item panel-block",
    },
    loading: {
        fullPageClass: "is-full-page",
        overlayClass: "loading-overlay",
        iconClass: "icon",
        rootClass: "loading",
        scrollClipClass: "is-clipped",
    },
    tree: {
        rootClass: "tree menu",
        listClass: "menu-list",
        disabledClass: "is-disabled",
        emptyClass: "is-empty",
        itemClass: "tree-item",
        itemLabelClass: "menu-item",
        itemIconClass: "tree-icon",
        itemToggleIconClass: "tree-toggle-icon",
        itemSelectedClass: "is-active",
        itemDisabledClass: "is-disabled",
        subtreeClass: "submenu",
    },
    upload: {
        rootClass: "upload control",
        variantClass: "is-",
        expandedClass: "is-expanded",
        disabledClass: "is-disabled",
        draggableClass: "upload-draggable",
        draggableHoveredClass: "is-hovered",
    },
};

export { bulmaConfig, bulmaConfig as config };
